springfox:
  documentation:
    # 总开关（同时设置auto-startup=false，否则/v3/api-docs等接口仍能继续访问）
    enabled: true
    auto-startup: true
    swagger-ui:
      enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # mysql 配置
  datasource:
    url: jdbc:mysql://120.55.75.238:13316/bigdata-backstage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Test806@mysqlYitong
  # redis 配置
  redis:
    host: 120.55.75.238 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: tzgfdn # Redis服务器连接密码（默认为空）
    timeout: 3000 # 连接超时时间（毫秒）

logging:
  file:
    path: /home/bigdata/logs
  level:
    root: info
    com.bigdata.backstage: debug

