springfox:
  documentation:
    # 总开关（同时设置auto-startup=false，否则/v3/api-docs等接口仍能继续访问）
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # mysql 配置
  datasource:
    url: jdbc:mysql://10.62.131.37:3306/bigdata-backstage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ytbig
    password: YtBig@2022
  # redis 配置
  redis:
    host: 10.62.131.40 # Redis服务器地址
    database: 5 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 10000 # 连接超时时间（毫秒）

logging:
  file:
    path: /home/micros/bigdata-backstage-backend/logs
  level:
    root: info
    com.bigdata.backstage: debug


